#=== Project ===

project.fullname = "Corona-Rechtsprechung des Bundesverfassungsgerichts"
project.shortname = "BVerfG-Corona"
project.author = "Seán Fobbe"



#=== License ===

license.data = "Creative Commons Zero 1.0 Universal"
license.code = "MIT-0"


#=== Main Data Set ===
# Dieser Datumsstempel wird in alle Dateinamen eingefügt. Er richtet sich nach der Version des Stamm-Datensatzes.

cebverfg.date = "2022-08-24"
cebverfg.doi.data.version = "10.5281/zenodo.7011305" # Aus diesem Datensatz werden die Entscheidungen bezogen.



#=== Digital Object Identifier (DOI) ===

# In diesen Datensatz werden die Corona-relevanten Entscheidungen überführt.
doi.data.concept = "10.5281/zenodo.4459405" # do not change
doi.data.version = "10.5281/zenodo.7062767" # checked

doi.software.concept = "10.5281/zenodo.4459415" # do not change
doi.software.version = "10.5281/zenodo.7062768" # checked





#=== Parallelization ===

cores.max = true  # Ob die maximale Anzahl an logischen Kernen genutzt werden soll; Möglichkeiten sind "true" oder "false"
cores.number = 8   # Die Anzahl Rechtenkerne, die verwendet werden soll; wird nur berücksichtigt falls "cores.max" auf "false" steht


parallel.multihashes = true



#=== Download ===
download.timeout = 600			# Timeout für Downloads



#=== Quanteda ===
quanteda.tokens_locale = "de_DE" # Locale in denen Tokens analyisert werden



#===  Knitr ===

fig.format = [ "pdf", "png" ] 	# Ausgabe-Format für Diagramme
fig.dpi = 300     	 	# Auflösung für Diagramme
fig.align = "center"    	# Ausrichtung von Diagrammen im Compilation Report



#=== Frequenztabellen: Ignorierte Variablen ===
#' **Hinweis:** Diese Variablen werden bei der Erstellung der Frequenztabellen nicht berücksichtigt.

freqtable.ignore = ["text",
		    "eingangsnummer",
              	    "datum",
               	    "doc_id",
               	    "seite",
               	    "name",
               	    "ecli",
               	    "aktenzeichen",
               	    "aktenzeichen_alle",
               	    "zeichen",
               	    "tokens",
               	    "typen",
               	    "saetze",
               	    "version",
               	    "pressemitteilung",
               	    "zitiervorschlag",
               	    "kurzbeschreibung",
		    "url_pdf",
		    "url_html"]
