[project]

fullname = "Corona-Rechtsprechung des Bundesverfassungsgerichts"
shortname = "BVerfG-Corona"
author = "Seán Fobbe"


[license]

data = "Creative Commons Zero 1.0 Universal"
code = "MIT-0"


#=== Main Data Set ===
# Dieser Datumsstempel wird in alle Dateinamen eingefügt. Er richtet sich nach der Version des Stamm-Datensatzes.

[cebverfg]

date = "2023-02-26"
doi.data.version = "10.5281/zenodo.7659109" # Aus diesem Datensatz werden die Entscheidungen bezogen.





[doi] # Digital Object Identifier (DOI)

# In diesen Datensatz werden die Corona-relevanten Entscheidungen überführt.

data.concept = "10.5281/zenodo.4459405" # do not change
data.version = "10.5281/zenodo.7062767" # checked

software.concept = "10.5281/zenodo.4459415" # do not change
software.version = "10.5281/zenodo.7062768" # checked





[cores]

max = true  # Ob die maximale Anzahl an logischen Kernen genutzt werden soll; Möglichkeiten sind "true" oder "false"
number = 8   # Die Anzahl Rechtenkerne, die verwendet werden soll; wird nur berücksichtigt falls "cores.max" auf "false" steht


[parallel]

multihashes = true



[download]

timeout = 600			# Timeout für Downloads



[quanteda]

tokens_locale = "de_DE" # Locale in denen Tokens analyisert werden



[fig] #  Knitr

format = [ "pdf", "png" ] 	# Ausgabe-Format für Diagramme
dpi = 300     	 	# Auflösung für Diagramme
align = "center"    	# Ausrichtung von Diagrammen im Compilation Report




[freqtable]

#' Diese Variablen werden bei der Erstellung der Frequenztabellen nicht berücksichtigt.

ignore = ["text",
       	  "eingangsnummer",
	  "datum",
	  "doc_id",
	  "seite",
	  "name",
	  "ecli",
	  "aktenzeichen",
	  "aktenzeichen_alle",
	  "zeichen",
	  "tokens",
	  "typen",
	  "saetze",
	  "version",
	  "pressemitteilung",
	  "zitiervorschlag",
	  "kurzbeschreibung",
	  "url_pdf",
	  "url_html"]
