# This script will delete all data and targets generated by the data set creation process. Run if you wish to do a hard reset for a fresh rerun.

targets::tar_destroy(ask = FALSE)


delete1 <- c("files/",
            "netzwerke",
            "temp/",
            "analysis/",
            "output/",
            "data")


delete2 <- list.files(pattern = "\\.zip|\\.xml|\\.jpe?g|\\.png|\\.gif|\\.pdf|\\.epub|\\.bib|\\.csv|\\.dtd|\\.spin\\.|\\.log|\\.gpg|\\.html",
                           ignore.case = TRUE)


delete <- c(delete1, delete2)

unlink(delete, recursive = TRUE)
