version: "3.7"

services:
  bverfg-corona:
    container_name: bverfg-corona
    image: bverfg-corona:4.4.0
    tty: true
    volumes:
      - .:/bverfg-corona
      - ./etc/gitconfig:/etc/gitconfig
    environment:
      - TZ=Europe/Berlin